config/routes.rb
Rails.application.routes.draw do
  get     "login"    => "session#new"
  post    "login"    => "session#create"
  delete  "logout"   => "session#destroy"

  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
	has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionHelper
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def index
  end
  
  def new
  end

  def create
    user = User.find_by name: params[:session][:name].downcase
    if user && user.authenticate(params[:session][:password])
      flash[:success] = "Login success"
      log_in user
      redirect_to user
    else
      flash[:danger] = "Invalid email/password combination"
      render :new
    end
  end

  def destroy
    log_out
    flash[:success] = "You are logged out"
    redirect_to login_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @user = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      flash[:success] = "Register success"
      redirect_to users_path
    else
      flash[:success] = "Register failed"
      render :new
    end
  end
  
  def show
    @user = User.find_by id: params[:id]
  end

  private
  def user_params
    params.require(:user).permit :name, :password, :password_confirmation
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/session_helper.rb
module SessionHelper
  def log_in user
    session[:user_id] = user.id
  end
  
  def log_out
    session.delete :user_id
  end
  
  def current_user
    @current_user ||= User.find_by id: session[:user_id]
  end

  def logged_in?
    current_user.present?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AuthenticationDemo</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <section class="content" style="min-height: auto;">
      <% flash.each do |key, value| %>
        <div class="row">
          <div class="alert alert-<%= key %>">
            <%= value %>
          </div>
        </div>
      <% end %>
    </section>
    <%= yield %>
  </body>
</html>

app/views/session/new.html.erb
<main>  
  <div class="device">
    <header></header>
    <section>
      <div class="weather time-morning active">
        <div class="icon">
          <i class="sun"></i>
        </div>
        <div class="content">
          <h3>Morning</h3>
          <div class="degrees">- 1</div>
          <div class="data">          
            <h2>Sunny</h2>
            <div>Wind: E 7 mph</div>
            <div>Humidity: 91%</div>
          </div>
        </div>
      </div>
      <div class="weather time-day">
        <div class="icon">
          <i class="sun"></i>
          <i class="cloud windy"></i>
        </div>
        <div class="content">
          <h3>Day</h3>
          <div class="degrees">+ 3</div>
          <div class="data">          
            <h2>Mostly Sunny</h2>
            <div>Wind: N 5 mph</div>
            <div>Humidity: 45%</div>
          </div>
        </div>
      </div>
      <div class="weather time-evening">
        <div class="icon">
          <i class="sun"></i>
          <i class="cloud"></i>
          <i class="sprinkles"></i>
          <i class="sprinkles"></i>
          <i class="sprinkles"></i>
          <i class="sprinkles"></i>
        </div>
        <div class="content">
          <h3>Evening</h3>
          <div class="degrees">0</div>
          <div class="data">          
            <h2>Rainy</h2>
            <div>Wind: W 12 mph</div>
            <div>Humidity: 91%</div>
          </div>
        </div>
      </div>
      <div class="weather time-night">
        <div class="icon">
          <i class="moon"></i>
          <i class="cloud"></i>
          <div class="snowflakes">
            <i class="snowflake"></i>
            <i class="snowflake"></i>
            <i class="snowflake"></i>
            <i class="snowflake"></i>
          </div>
        </div>
        <div class="content">
          <h3>Night</h3>
          <div class="degrees">- 2</div>
          <div class="data">          
            <h2>Cloudy</h2>
            <div>Wind: N 2 mph</div>
            <div>Humidity: 47%</div>
          </div>
        </div>
      </div>
    </section>
  </div>
</main>

<aside>
  <div class="row">
    <h1 class="title">Login</h1>
  </div>
  <div class="row">
    <div class="col-lg-offset-3 col-lg-6">
      <%= form_for :session, url: login_path do |f| %>
        <div class="form-group">
          <%= f.label :name %>
          <%= f.text_field :name, placeholder: "Enter your name", class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :password %>
          <%= f.password_field :password, placeholder: "Enter your password",
            class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.submit "Login", class: "btn btn-info col-lg-12" %>
		  <%= link_to "Register", new_user_path, style: "float: right;"%>
        </div>
      <% end %>
    </div>
  </div>
</aside>

app/views/users/_user.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-offset-3 col-lg-6">
      <div class="text-left col-lg-6", style="padding-left: 0px ">
        <label>User name: <%= @user.name %></label>
      </div>
      <div class="text-right col-lg-6">
        <%= link_to "Logout", logout_path, method: :delete %>
      </div>
    </div>
    <div class="col-lg-offset-3 col-lg-6">
      <%= link_to "List Users", users_path %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-12 text-center">
      <h1 class="title">LOGIN APP</h1>
    </div>
    <div class="col-lg-12 form-group">
      <label for="">Welcome</label>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="container">
	<div class="row">
		<h1 class="title">Register</h1>
	</div>
	<div class="row">
	  <div class="col-lg-offset-3 col-lg-6">
		<%= form_for @user, html: {class: "form-horizontal"} do |f| %>
		  <div class="form-group">
			<%= f.label :name, "Name" %>
			<%= f.text_field :name, class: "form-control", placeholder: "Enter user name" %>
		  </div>
		  <div class="form-group">
			<%= f.label :password, "Password" %>
			<%= f.password_field :password, class: "form-control", placeholder: "Enter password" %>
		  </div>
		  <div class="form-group">
			<%= f.label :password_confirmation, "Password Confirmation" %>
			<%= f.password_field :password_confirmation, class: "form-control", placeholder: "Enter password confirmation" %>
		  </div>
		  <div class="text-center">
			<%= f.submit "Register", class: "btn btn-info col-lg-12" %>
		  </div>
		<% end %>
	  </div>
	</div>
</div>

app/views/users/show.html.erb
<style>
body{
  counter-reset:birds;
  -webkit-touch-callout: none;
  -webkit-user-select: none;
  -khtml-user-select: none;
  -moz-user-select: none;
  -ms-user-select: none;
  user-select: none;
  overflow:hidden;
}
/*hide checkbox*/
input{position:fixed; left:-10px; top:-10px;}

h1{margin:0; text-align:center;}
h2{position:fixed; right:20px; bottom:0; font-size:18px; color:red;}

/*play area*/
.wrapper{  
  height:500px;
  background: -webkit-linear-gradient(top, hsla(210,70%,80%,1) 0%,hsla(210,50%,100%,1) 100%);
  position:relative;
  cursor:crosshair;
}
/*count dead birds*/
.input-circle:checked{
  counter-increment:birds;
}

.sum{position:fixed; left:45%; top:60px; font-size:24px; fonot-weight:bold;}

/*print to screen dead birds*/
.sum:after{
  content: counter(birds);
}

.input-circle ~ .pajaro{
  opacity:0;
  transition:0.3s  cubic-bezier(0,.43,1,0);
  animation: move 8s infinite alternate;
}
.input-circle1:not(:checked) ~ .pajaro1,
.input-circle2:not(:checked) ~ .pajaro2,
.input-circle3:not(:checked) ~ .pajaro3,
.input-circle4:not(:checked) ~ .pajaro4,
.input-circle5:not(:checked) ~ .pajaro5,
.input-circle6:not(:checked) ~ .pajaro6
{
  opacity:1; 
}


.input-circle1:checked ~ .pajaro1 span,
.input-circle2:checked ~ .pajaro2 span,
.input-circle3:checked ~ .pajaro3 span,
.input-circle4:checked ~ .pajaro4 span,
.input-circle5:checked ~ .pajaro5 span,
.input-circle6:checked ~ .pajaro6 span
{
  display:block;
  
}

.pajaro{   
  position:absolute;
  left:0;  
  cursor:crosshair;
}
.pajaro>span{
  display:none;position:absolute; z-index:2; left:-250%;bottom:-50%;  
  background-color:white; border:solid 2px #000; width:80px; height:30px; padding:10px; border-radius:50%;
}
.pajaro>span:before{
  content:"I'm Dead!"; color:red; font-weight:bold;
}

.pajaro1{top:50px;
  animation-delay: -2s!important;
  transform:scale(0.9);
}
.pajaro2{
  top:100px;
  animation-delay: -4s!important;
  transform:scale(0.5); 
}
.pajaro3{
  top:200px;
  animation-delay: -3s!important;
  transform:scale(1.4); 
}

.pajaro4{top:50px;
  animation-delay: -12s!important;
  transform:scale(0.9);
}
.pajaro5{
  top:100px;
  animation-delay: -16s!important;
  transform:scale(0.5); 
}
.pajaro6{
  top:200px;
  animation-delay: -20s!important;
  transform:scale(1.4); 
}

@keyframes move{
0%{left:0%;}
20%{left:20%;top:50%; }
40%{top:30%; left:60%;}
60%{top:80%;left:80%;}
80%{top:10%; left:20%;}
100%{top:30%; left:20%; }
}


.timer{
  background-color:#333; width:300px;height:50px;
  position:fixed;
}


.timer span{
  display:block;
  background:repeating-linear-gradient(-45deg, #000, rgba(0, 0, 0, 0) 25px, #FFF 25px, #FFF 50px);
  width:300px; height:50px;
  animation:timer 20s linear;
}

.timer span:before{  
  display:block;
  position:absolute; z-index:3;
  left:0; 
  right:0;
  top:0;
  bottom:0;
  text-align:center;
  line-height:50px;
  font-size:25px;
  color:red;
}
@keyframes timer{
0%{width:10px;}
100%{width:300px; display:block;}
}


.gameover{
  position:fixed; z-index:100000; left:0; top:0; bottom:0; right:0; background-color:rgba(0,0,0,0.8);
  animation:gameover 20s linear forwards;
  font-size:80px; color:white; font-weight:bold; text-align:center; 
  text-indent:0;  
  line-height:500px;
}

@keyframes gameover{
0%{left:-5000px;bottom:100%;}
97%{left:-5000px;bottom:100%;}
100%{ left:0px;}
}

footer{position:fixed; left:0; bottom:0;}




/*------------------------------------------------------ body of the bird
*/

.pajaro{
  background:black;
  border-radius: 50% 50% 20% 20%;
  color:white;
  line-height:20px;
  letter-spacing: 2px;
  font-size:0.8em;
  text-align:center;
  position:absolute;
 
  margin-top:-20px; margin-left:-10px;
  width:15px; height:15px;
  animation:planeo 0.8s linear infinite;
  z-index:999;
}

.pajaro:after,
.pajaro:before{
  content:"";
  position:absolute;
  top:50%; left:50%;
}

/*------------------------------------------------------ bird wings
*/

.pajaro:after{
  border-radius: 100% 100% 0 0;
  box-shadow: inset 0px 5px 0 black;
  width:100px; height:100px;
  margin-top:-7px; margin-left:-50px;
  transform-origin: 100% 0%;
  animation:alas 3s linear infinite;
}

/*------------------------------------------------------ bird beak
*/

.pajaro:before{
  background:#FFC37F;
  border-radius: 100% 0% 20% 0%;
  margin-top:3px; margin-left:-4px;
  width:6px; height:6px;
  transform:rotateZ(45deg);
}

/*------------------------------------------------------ wings animation
*/

@keyframes alas {
  50%{
    transform:rotateX(-1440deg);
  }
}

/*------------------------------------------------------ bird animation
*/

@keyframes planeo {
  40%{
    transform:rotateZ(2deg) translateX(2px) translateY(10px) translateZ(0);
    line-height:16px;
    font-size:0.6em;
  }
  80%{
    transform:rotateZ(-2deg) translateX(5px) translateY(8px) translateZ(0);
  }
}
</style>

<div class="wrapper">
  <div class="timer">
       <span></span>    
  </div>
  <div class="gameover">GAME OVER</div>
  <input class="input-circle input-circle1" type="radio" id="circle1" >
  <input class="input-circle input-circle2" type="radio" id="circle2" >
  <input class="input-circle input-circle3" type="radio" id="circle3" >
  <input class="input-circle input-circle4" type="radio" id="circle4" >
  <input class="input-circle input-circle5" type="radio" id="circle5" >
  <input class="input-circle input-circle6" type="radio" id="circle6" >
  
  <label for="circle1" class="pajaro pajaro1"><span></span></label>
  <label for="circle2" class="pajaro pajaro2"><span></span></label>
  <label for="circle3" class="pajaro pajaro3"><span></span></label>
  <label for="circle4" class="pajaro pajaro4"><span></span></label>
  <label for="circle5" class="pajaro pajaro5"><span></span></label>
  <label for="circle6" class="pajaro pajaro6"><span></span></label>
  <div class="sum">SCORE:</div>
</div>